name: CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}
    - name: Extract tag
      shell: bash
      run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/} | sed s:/:-:g)"
      id: extract_tag
    - name: Base image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/parisk/compose-cli:${{ steps.extract_tag.outputs.tag }}
        target: base
    - name: AWS image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/parisk/compose-cli:${{ steps.extract_tag.outputs.tag }}-aws
        target: aws
