name: GitLab Container Registry

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitLab
      uses: docker/login-action@v1
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_REGISTRY_USER }}
        password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
    - name: Extract tag
      shell: bash
      run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/} | sed s:/:-:g)"
      id: extract_tag
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: registry.gitlab.com/parisk/compose-cli:${{ steps.extract_tag.outputs.tag }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        file: aws.Dockerfile
        tags: registry.gitlab.com/parisk/compose-cli:${{ steps.extract_tag.outputs.tag }}-aws
        args: |
          BASE_IMAGE=registry.gitlab.com/parisk/compose-cli:${{ steps.extract_tag.outputs.tag }}
